# Generated by Django 3.1 on 2020-09-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20200919_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='item',
        ),
    ]
