# Generated by Django 3.1 on 2020-09-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_remove_cart_item_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='buyer.cart_item'),
            preserve_default=False,
        ),
    ]
